#!/usr/bin/env python

import sys
from os.path import dirname
anchor_dir = dirname(dirname(__file__))
sys.path.append(anchor_dir)
sys.path.append(f"{anchor_dir}/python")

from antlr4 import FileStream, CommonTokenStream, ParseTreeWalker
from generated.SMTLIB26Lexer import SMTLIB26Lexer
from generated.SMTLIB26Parser import SMTLIB26Parser
from generated.SMTLIB26ParserListener import SMTLIB26ParserListener

class MySMTLIB26Printer(SMTLIB26ParserListener):
    def enterIdentifier(self, ctx):
        print(ctx.symbol().SIMPLE_SYMBOL())

def main(argv):
    input = FileStream(argv[1])
    lexer = SMTLIB26Lexer(input)
    stream = CommonTokenStream(lexer)
    parser = SMTLIB26Parser(stream)
    tree = parser.script()
    walker = ParseTreeWalker()
    walker.walk(MySMTLIB26Printer(), tree)

if __name__ == '__main__':
    main(sys.argv)
